trigger: none    
jobs:
  - job: 'create_release'  
    steps:
    - task: GithubRelease@0
      displayName: 'Create GitHub Release'
      inputs:
        gitHubConnection: AzureConnection
        repositoryName: JayanthiRamadass/jay 
        tagSource: manual                     
        tag: $(Build.BuildNumber)   
        assets: |
           $(Build.ArtifactStagingDirectory)/*.exe
           $(Build.ArtifactStagingDirectory)/README.txt
